guis:
  main_menu:
    title: "&6TEST MENU"
    size: 27
    items:
      item1:
        slot: 10
        material: DIAMOND_SWORD
        name: "&aMeč Bojovníka"
        lore:
          - "&7Klikni pro získání meče!"
        action:
          type: COMMAND
          value: "give %player% diamond_sword 1"
      item2:
        slot: 12
        material: BOOK
        name: "&ePravidla"
        lore:
          - "&7Zobrazí pravidla serveru."
        action:
          type: MESSAGE
          value: "Pravidla: Buď slušný a necheatuj!"